# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-01-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default='-1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_related', to='courses.Teacher'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(default='-1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_related', to='courses.Teacher'),
        ),
        migrations.AddField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(default='-1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_related', to='courses.Teacher'),
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(default='-1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_related', to='courses.Teacher'),
        ),
    ]
