# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-01-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190104_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses_joined',
            field=models.ManyToManyField(related_name='students', through='courses.Booking', to='courses.Course'),
        ),
    ]
